# Generated by Django 4.2.3 on 2025-09-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_rename_course_choice_question_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='order',
            new_name='grade',
        ),
    ]
